# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='组名')),
            ],
        ),
        migrations.AddField(
            model_name='userinof',
            name='m2m',
            field=models.ManyToManyField(blank=True, null=True, to='app01.Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=32, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='userinof',
            name='email',
            field=models.CharField(max_length=32, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinof',
            name='user',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='userinof',
            name='ug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.UserGroup'),
        ),
    ]
